with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceNameSnake}}.go"
all: True
packages:
  github.com/walletera/eventskit/events:
    interfaces:
      Handler:
      Deserializer:
      EventData:
  github.com/walletera/eventskit/fake:
    interfaces:
      EventHandler:
  github.com/walletera/eventskit/messages:
      interfaces:
        Consumer:
        Acknowledger:
