with-expecter: True
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceNameSnake}}.go"
all: True
packages:
  github.com/walletera/message-processor/events:
    interfaces:
      Handler:
      Deserializer:
  github.com/walletera/message-processor/fake:
    interfaces:
      EventVisitor:
  github.com/walletera/message-processor/messages:
      interfaces:
        Consumer:
        Acknowledger:
